### ISSUE TITLE
SkyPiratesGunDev - test and develop fix to droppy bombos

### ISSUE THREAD

**Issue by xianson** [StarCoreSE/TLB#19]
current fix may not work, need to test it on ds. previous behavior was a client only audio bug. soln was to perform razeblock server side only. may nt wrk

**Comment by InvalidArgument3** [comment]
it seems to be fine on DS thanks to razeblock that's the correct one to use

**Comment by InvalidArgument3** [comment]
nope still fucked
this is the keen audio crash, WC guys report the same thing
something about the audio sbc. another workaround is "converting to .xwm"

```
2024-07-28 11:45:48.820 - Thread:   1 ->  Exception occurred: SharpDX.SharpDXException: HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, Nullable`1 bufferWMARef)
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, UInt32[] decodedXMWAPacketInfo)
   at VRage.Audio.MySourceVoice.Start(Boolean skipIntro, Boolean skipToEnd)
   at VRage.Audio.MyXAudio2.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd, Boolean isMusic)
   at VRage.Audio.MyXAudio2.VRage.Audio.IMyAudio.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundInternal(Boolean skipIntro, Boolean skipToEnd, Boolean force2D, Boolean alwaysHearOnRealistic, Nullable`1 force3D)
2024-07-28 11:45:48.820 - Thread:   1 ->  Last null written by: 
2024-07-28 11:45:48.944 - Thread:   1 ->  Exception: SharpDX.SharpDXException: HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, Nullable`1 bufferWMARef)
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, UInt32[] decodedXMWAPacketInfo)
   at VRage.Audio.MySourceVoice.Start(Boolean skipIntro, Boolean skipToEnd)
   at VRage.Audio.MyXAudio2.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd, Boolean isMusic)
   at VRage.Audio.MyXAudio2.VRage.Audio.IMyAudio.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundInternal(Boolean skipIntro, Boolean skipToEnd, Boolean force2D, Boolean alwaysHearOnRealistic, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundWithDistance(MyCueId soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean useDistanceCheck, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySound(MySoundPair soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D, Boolean forcePlaySound)
   at Sandbox.Game.Weapons.MyGunBase.StartShootSound(MyEntity3DSoundEmitter soundEmitter, Boolean force2D)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.OnShootMissile(MyObjectBuilder_Missile builder)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3](T1 arg1, T3 arg3, Func`2 action, T2 arg2, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Engine.Multiplayer.MyMultiplayer.RaiseEvent[T1,T2](T1 arg1, Func`2 action, T2 arg2, EndpointId targetEndpoint)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.ShootMissile(MyObjectBuilder_Missile builder)
   at Sandbox.Game.Weapons.MyGunBase.AddMissile(MyWeaponPropertiesWrapper weaponProperties, Vector3D initialPosition, Vector3 initialVelocity, Vector3 direction, MyEntity controller)
   at Sandbox.Game.Weapons.MyGunBase.Shoot(Vector3D initialPosition, Vector3 initialVelocity, Vector3 direction, MyEntity owner, Nullable`1 renderId, Boolean userNormalizedPositionForEffects)
   at Sandbox.Game.Weapons.MyGunBase.Shoot(Vector3 initialVelocity, MyEntity owner, Nullable`1 renderId)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.ShootMissile(Vector3 velocity)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.ShootMissile()
   at Sandbox.Game.Weapons.MySmallMissileLauncher.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-28 11:45:48.948 - Thread:   1 ->  Exception occurred: SharpDX.SharpDXException: HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, Nullable`1 bufferWMARef)
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, UInt32[] decodedXMWAPacketInfo)
   at VRage.Audio.MySourceVoice.Start(Boolean skipIntro, Boolean skipToEnd)
   at VRage.Audio.MyXAudio2.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd, Boolean isMusic)
   at VRage.Audio.MyXAudio2.VRage.Audio.IMyAudio.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundInternal(Boolean skipIntro, Boolean skipToEnd, Boolean force2D, Boolean alwaysHearOnRealistic, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundWithDistance(MyCueId soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean useDistanceCheck, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySound(MySoundPair soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D, Boolean forcePlaySound)
   at Sandbox.Game.Weapons.MyGunBase.StartShootSound(MyEntity3DSoundEmitter soundEmitter, Boolean force2D)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.OnShootMissile(MyObjectBuilder_Missile builder)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3](T1 arg1, T3 arg3, Func`2 action, T2 arg2, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Engine.Multiplayer.MyMultiplayer.RaiseEvent[T1,T2](T1 arg1, Func`2 action, T2 arg2, EndpointId targetEndpoint)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.ShootMissile(MyObjectBuilder_Missile builder)
   at Sandbox.Game.Weapons.MyGunBase.AddMissile(MyWeaponPropertiesWrapper weaponProperties, Vector3D initialPosition, Vector3 initialVelocity, Vector3 direction, MyEntity controller)
   at Sandbox.Game.Weapons.MyGunBase.Shoot(Vector3D initialPosition, Vector3 initialVelocity, Vector3 direction, MyEntity owner, Nullable`1 renderId, Boolean userNormalizedPositionForEffects)
   at Sandbox.Game.Weapons.MyGunBase.Shoot(Vector3 initialVelocity, MyEntity owner, Nullable`1 renderId)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.ShootMissile(Vector3 velocity)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.ShootMissile()
   at Sandbox.Game.Weapons.MySmallMissileLauncher.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2024-07-28 11:45:48.948 - Thread:   1 ->  Showing message
2024-07-28 11:45:48.950 - Thread:   1 ->  MyInitializer.OnCrash
2024-07-28 11:45:48.950 - Thread:   1 ->  var exception = SharpDX.SharpDXException: HRESULT: [0x88960001], Module: [SharpDX.XAudio2], ApiCode: [XAUDIO2_E_INVALID_CALL/InvalidCall], Message: Unknown
   at SharpDX.Result.CheckError()
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, Nullable`1 bufferWMARef)
   at SharpDX.XAudio2.SourceVoice.SubmitSourceBuffer(AudioBuffer bufferRef, UInt32[] decodedXMWAPacketInfo)
   at VRage.Audio.MySourceVoice.Start(Boolean skipIntro, Boolean skipToEnd)
   at VRage.Audio.MyXAudio2.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd, Boolean isMusic)
   at VRage.Audio.MyXAudio2.VRage.Audio.IMyAudio.PlaySound(MyCueId cueId, IMy3DSoundEmitter source, MySoundDimensions type, Boolean skipIntro, Boolean skipToEnd)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundInternal(Boolean skipIntro, Boolean skipToEnd, Boolean force2D, Boolean alwaysHearOnRealistic, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySoundWithDistance(MyCueId soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean useDistanceCheck, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D)
   at Sandbox.Game.Entities.MyEntity3DSoundEmitter.PlaySound(MySoundPair soundId, Boolean stopPrevious, Boolean skipIntro, Boolean force2D, Boolean alwaysHearOnRealistic, Boolean skipToEnd, Nullable`1 force3D, Boolean forcePlaySound)
   at Sandbox.Game.Weapons.MyGunBase.StartShootSound(MyEntity3DSoundEmitter soundEmitter, Boolean force2D)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.OnShootMissile(MyObjectBuilder_Missile builder)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3](T1 arg1, T3 arg3, Func`2 action, T2 arg2, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Engine.Multiplayer.MyMultiplayer.RaiseEvent[T1,T2](T1 arg1, Func`2 action, T2 arg2, EndpointId targetEndpoint)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.ShootMissile(MyObjectBuilder_Missile builder)
   at Sandbox.Game.Weapons.MyGunBase.AddMissile(MyWeaponPropertiesWrapper weaponProperties, Vector3D initialPosition, Vector3 initialVelocity, Vector3 direction, MyEntity controller)
   at Sandbox.Game.Weapons.MyGunBase.Shoot(Vector3D initialPosition, Vector3 initialVelocity, Vector3 direction, MyEntity owner, Nullable`1 renderId, Boolean userNormalizedPositionForEffects)
   at Sandbox.Game.Weapons.MyGunBase.Shoot(Vector3 initialVelocity, MyEntity owner, Nullable`1 renderId)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.ShootMissile(Vector3 velocity)
   at Sandbox.Game.Weapons.MySmallMissileLauncher.ShootMissile()
   at Sandbox.Game.Weapons.MySmallMissileLauncher.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.UpdateAfterSimulation()
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```
